name: Update Project

# Every Monday at 1PM UTC (9AM EST)
on:
  push:
  schedule:
      - cron: '0 13 * * 1' 

# Run jobs
jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    
    # Setup python for the runner
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    # Install needed dependencies
    - name: Install dependencies
      run: |
        python -m pip install -r requiriments.txt
        
    # Generate the new maps
    - name: Generate docs
      run: |
        python gen_maps.py
    
    # Next, we need to commit the new files into the repository
    - name: Commit files
      run: |
        git config --local user.name "sahahn"
        git add docs
        git add maps
        git commit -m "Update Maps"

    # Push the change
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true